const DISCONNECT_WEB_SOCKET = 'DISCONNECT_WEB_SOCKET';
// const RECEIVE_USER_EVENT = 'RECEIVE_USER_EVENT';
// const RECEIVE_CHAT_EVENT = 'RECEIVE_CHAT_EVENT';
const RECEIVE_WEB_SOCKET_EVENT = 'RECEIVE_WEB_SOCKET_EVENT';
// const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';

export {
    DISCONNECT_WEB_SOCKET,
    // RECEIVE_USER_EVENT,
    // RECEIVE_CHAT_EVENT,
    RECEIVE_WEB_SOCKET_EVENT,
    // SEND_CHAT_MESSAGE,
};
