const RECEIVE_USER_EVENT = 'RECEIVE_USER_EVENT';
const RECEIVE_CHAT_EVENT = 'RECEIVE_CHAT_EVENT';
const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';

export {
    RECEIVE_USER_EVENT,
    RECEIVE_CHAT_EVENT,
    SEND_CHAT_MESSAGE,
};
